"""Opaque identifiers owned and generated by Ophanim Core."""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID, uuid4

from .errors import DomainValidationError


def _uuid(value: UUID | str) -> UUID:
    if isinstance(value, UUID):
        return value
    if isinstance(value, str):
        try:
            return UUID(value)
        except ValueError as exc:
            raise DomainValidationError("identifier must be a valid UUID") from exc
    raise DomainValidationError("identifier must be a UUID or UUID string")


@dataclass(frozen=True, slots=True)
class TaskId:
    value: UUID

    def __post_init__(self) -> None:
        object.__setattr__(self, "value", _uuid(self.value))

    @classmethod
    def new(cls) -> TaskId:
        return cls(uuid4())

    @classmethod
    def from_str(cls, value: str) -> TaskId:
        return cls(value)

    def __str__(self) -> str:
        return str(self.value)


@dataclass(frozen=True, slots=True)
class TaskStepId:
    value: UUID

    def __post_init__(self) -> None:
        object.__setattr__(self, "value", _uuid(self.value))

    @classmethod
    def new(cls) -> TaskStepId:
        return cls(uuid4())

    @classmethod
    def from_str(cls, value: str) -> TaskStepId:
        return cls(value)

    def __str__(self) -> str:
        return str(self.value)


@dataclass(frozen=True, slots=True)
class CorrelationId:
    value: UUID

    def __post_init__(self) -> None:
        object.__setattr__(self, "value", _uuid(self.value))

    @classmethod
    def new(cls) -> CorrelationId:
        return cls(uuid4())

    @classmethod
    def from_str(cls, value: str) -> CorrelationId:
        return cls(value)

    def __str__(self) -> str:
        return str(self.value)


@dataclass(frozen=True, slots=True)
class ProjectId:
    value: UUID

    def __post_init__(self) -> None:
        object.__setattr__(self, "value", _uuid(self.value))

    @classmethod
    def new(cls) -> ProjectId:
        return cls(uuid4())

    @classmethod
    def from_str(cls, value: str) -> ProjectId:
        return cls(value)

    def __str__(self) -> str:
        return str(self.value)


@dataclass(frozen=True, slots=True)
class AgentRunId:
    value: UUID

    def __post_init__(self) -> None:
        object.__setattr__(self, "value", _uuid(self.value))

    @classmethod
    def new(cls) -> AgentRunId:
        return cls(uuid4())

    @classmethod
    def from_str(cls, value: str) -> AgentRunId:
        return cls(value)

    def __str__(self) -> str:
        return str(self.value)


@dataclass(frozen=True, slots=True)
class QualityGateRunId:
    value: UUID

    def __post_init__(self) -> None:
        object.__setattr__(self, "value", _uuid(self.value))

    @classmethod
    def new(cls) -> QualityGateRunId:
        return cls(uuid4())

    @classmethod
    def from_str(cls, value: str) -> QualityGateRunId:
        return cls(value)

    def __str__(self) -> str:
        return str(self.value)


@dataclass(frozen=True, slots=True)
class ReviewResultId:
    value: UUID

    def __post_init__(self) -> None:
        object.__setattr__(self, "value", _uuid(self.value))

    @classmethod
    def new(cls) -> ReviewResultId:
        return cls(uuid4())

    @classmethod
    def from_str(cls, value: str) -> ReviewResultId:
        return cls(value)

    def __str__(self) -> str:
        return str(self.value)


@dataclass(frozen=True, slots=True)
class WorkflowEventId:
    value: UUID

    def __post_init__(self) -> None:
        object.__setattr__(self, "value", _uuid(self.value))

    @classmethod
    def new(cls) -> WorkflowEventId:
        return cls(uuid4())

    @classmethod
    def from_str(cls, value: str) -> WorkflowEventId:
        return cls(value)

    def __str__(self) -> str:
        return str(self.value)
